### PR TITLE
Remove OrdinaryDiffEq.jl dependency

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR removes the OrdinaryDiffEq.jl dependency in favor of using SciMLBase.

### CODE REVIEW

**Review by juliasloan25 — APPROVED** [review]
Looks good, thank you Charlie!

**Comment by charleskawczynski** [comment]
ok, hopefully last fix

**Comment by kmdeck** [comment]
this might fail because I bors r+ed a PR about 30 minutes ago - if so, I can rebase and merge this for you once that is in!

**Pull request merged**
