### PR TITLE
Soil canopy water conservation

### PR DESCRIPTION
**Pull request by kmdeck**
## Purpose 
Adds a short run computing water balance for the soil+canopy model; makes a plot and uploads to buildkite.

## Content
Adds experiment to buildkite

Review checklist

I have:
- followed the codebase contribution guide: https://clima.github.io/ClimateMachine.jl/latest/Contributing/
- followed the style guide: https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/
- followed the documentation policy: https://github.com/CliMA/policies/wiki/Documentation-Policy
- checked that this PR does not duplicate an open PR.

In the Content, I have included 
- relevant unit tests, and integration tests, 
- appropriate docstrings on all functions, structs, and modules, and included relevant documentation.

----
- [X] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by kmdeck** [comment]
water_conservation

**Comment by AlexisRenchon** [comment]
hmm not sure why ci breaks 
```
Test Summary:                                           | Error  Total   Time
Test set_initial_parameter_field for BulkAlbedoTemporal |     1      1  44.1s

in expression starting at /home/runner/work/ClimaLSM.jl/ClimaLSM.jl/test/standalone/Bucket/albedo_types.jl:102
```
possibly from box?
```
RequestError: HTTP/2 200 (HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)) while requesting https://caltech.box.com/shared/static/h3fcq4hlfe0o4kaj7ghftv76tg7v879v.nc
```
But the download starts and works well for me when I click on the link manually

**Comment by AlexisRenchon** [comment]
> > hmm not sure why ci breaks
> > ```
> > Test Summary:                                           | Error  Total   Time
> > Test set_initial_parameter_field for BulkAlbedoTemporal |     1      1  44.1s
> > 
> > in expression starting at /home/runner/work/ClimaLSM.jl/ClimaLSM.jl/test/standalone/Bucket/albedo_types.jl:102
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > possibly from box?
> > ```
> > RequestError: HTTP/2 200 (HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)) while requesting https://caltech.box.com/shared/static/h3fcq4hlfe0o4kaj7ghftv76tg7v879v.nc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But the download starts and works well for me when I click on the link manually
> > Looks like some errors with BulkAlbedo ... @juliasloan25
> 
> Thanks @AlexisRenchon! I retried it and it looks like it worked - so maybe just a one-off connection issue?

wow it's scary that such one-off connection issue happens. Could have been trying to debug for ages without knowing the code was actually working!

**Review by AlexisRenchon — APPROVED** [review]
Pretty straight-forward and passes CI!

**Comment by kmdeck** [comment]
> wow it's scary that such one-off connection issue happens. Could have been trying to debug for ages without knowing the code was actually working!

agreed!!

**Pull request merged**
