### PR TITLE
improving comparison to data at Ozark site

### PR DESCRIPTION
**Pull request by kmdeck**
## Purpose 
Test hypotheses for improving the simulation.

## To-do
1. increase amplitude of GPP and T in summer [leaf water potential too low -> stomatal conductance too low?]
2. decrease soil evaporation early in the year [issue with soil temperature or soil parameters? or influence of canopy which is not taken into account?]
3. improve sensible heat flux errors

## Content
- made nicer plots

Review checklist

I have:
- followed the codebase contribution guide: https://clima.github.io/ClimateMachine.jl/latest/Contributing/
- followed the style guide: https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/
- followed the documentation policy: https://github.com/CliMA/policies/wiki/Documentation-Policy
- checked that this PR does not duplicate an open PR.

In the Content, I have included 
- relevant unit tests, and integration tests, 
- appropriate docstrings on all functions, structs, and modules, and included relevant documentation.

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by kmdeck** [comment]
soil_temperature
water_fluxes
leaf_water_potential
cumul_p_et
shf
soil_water_content
stomatal_conductance
moisture_stress
ET
VPD
GPP
SW_IN

**Comment by braghiere** [comment]
Thanks! It looks like the problem is with moisture stress factor. It goes rapidly to zero during summer time and kills GPP and ET in mid Summer. The water potentials look way too underestimated by the model. We need to review that.

**Comment by AlexisRenchon** [comment]
What are GPP units? umol / mol is weird (on the figure title)
Could be umol (CO2) m-2 s-1
if data goes up to 40 umol m-2 s-1, that is definitely weird data to me. we should plot ecosystem respiration (ER) see if it looks reasonable. overestimated ER would lead to overestimated GPP is those datasets

**Comment by kmdeck** [comment]
Updated plots:
leaf_water_potential
cumul_p_et
ET
GPP
soil_water_content

**Comment by kmdeck** [comment]
These changes are already in main, so I am closing this branch

**Pull request closed without merging**
