### PR TITLE
Abstract Models tutorial

### PR DESCRIPTION
**Pull request by kmdeck**
Adding a short tutorial about how to create a model.

### CODE REVIEW

**Comment by kmdeck** [comment]
bors try

**Comment by kmdeck** [comment]
bors try

**Comment by kmdeck** [comment]
bors try

**Comment by kmdeck** [comment]
bors try

**Comment by kmdeck** [comment]
bors try

**Comment by kmdeck** [comment]
bors try

**Comment by kmdeck** [comment]
bors try

**Comment by kmdeck** [comment]
bors try

**Comment by kmdeck** [comment]
bors try

**Comment by kmdeck** [comment]
bors try

**Comment by kmdeck** [comment]
bors try

**Comment by kmdeck** [comment]
bors cancel

**Comment by kmdeck** [comment]
bors try-

**Comment by kmdeck** [comment]
bors try

**Comment by kmdeck** [comment]
@jb-mackay  I think this is ready to merge, but should we hold off until we update `initialize`? or we can update `initialize` and then update the tutorial to reflect those changes. Either way seems ok?

**Review by jb-mackay — APPROVED** [review]

**Comment by jb-mackay** [comment]
> @jb-mackay I think this is ready to merge, but should we hold off until we update `initialize`? or we can update `initialize` and then update the tutorial to reflect those changes. Either way seems ok?

It seems like updating `initialize` will take a bit of time, so let's get this merged so that it can be available as a resource!

**Pull request merged**
