### PR TITLE
Add windows run to CI

### PR DESCRIPTION
**Pull request by kmdeck**
## Purpose 
We test our CI on mac and linux OS - This PR adds a run on windows

## Content
Change to buildkite.yml
- [x] add to buildkite.yml
- [x] move tests using TempestRemap inside if statement (don't run on windows)
- [x] update README with windows limitation

## Review checklist
I have:
- followed the codebase contribution guide: https://clima.github.io/ClimateMachine.jl/latest/Contributing/
- followed the style guide: https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/
- followed the documentation policy: https://github.com/CliMA/policies/wiki/Documentation-Policy
- checked that this PR does not duplicate an open PR.

In the Content, I have included 
- relevant unit tests, and integration tests, 
- appropriate docstrings on all functions, structs, and modules, and included relevant documentation.

----
- [X] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by juliasloan25** [comment]
I just remembered that TempestRemap isn't built on Windows (I think because NetCDF doesn't support windows? Or at least not all of its functionality works on windows)

**Comment by juliasloan25** [comment]
To get around the TempestRemap issue and still have CI on windows, we could add an if statement so that code that uses TempestRemap doesn't get run on windows (like we do for FileReader tests [here](https://github.com/CliMA/ClimaLSM.jl/blob/main/test/shared_utilities/file_reader.jl#L179))

**Comment by kmdeck** [comment]
> To get around the TempestRemap issue and still have CI on windows, we could add an if statement so that code that uses TempestRemap doesn't get run on windows (like we do for FileReader tests [here](https://github.com/CliMA/ClimaLSM.jl/blob/main/test/shared_utilities/file_reader.jl#L179))

ok! and then we would just clarify (in the README?) that certain features are not available on windows? (this would be global runs, I guess?)

**Comment by juliasloan25** [comment]
> > To get around the TempestRemap issue and still have CI on windows, we could add an if statement so that code that uses TempestRemap doesn't get run on windows (like we do for FileReader tests [here](https://github.com/CliMA/ClimaLSM.jl/blob/main/test/shared_utilities/file_reader.jl#L179))
> 
> ok! and then we would just clarify (in the README?) that certain features are not available on windows? (this would be global runs, I guess?)

Yeah that sounds good!

**Review by kmdeck — COMMENTED** [review]
Thanks Julia! small PR and easy to review. looks good.

**Review by juliasloan25 — APPROVED** [review]

**Pull request merged**
