### PR TITLE
upgrade to 1.8, latest CC and SF

### PR DESCRIPTION
**Pull request by kmdeck**
# PULL REQUEST

## Purpose and Content
- upgrade to latest CC
- upgrade to latest SurfaceFluxes
- test with julia 1.8 in CI
- IntervalSets compat with CA

## PR Checklist
- [X] This PR has a corresponding issue OR is linked to an SDI.
- [x] I have followed CliMA's codebase [contribution](https://clima.github.io/ClimateMachine.jl/latest/Contributing/) and [style](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) guidelines OR N/A.
- [x] I have followed CliMA's [documentation policy](https://github.com/CliMA/policies/wiki/Documentation-Policy).
- [x] I have checked all issues and PRs and I certify that this PR does not duplicate an open PR.
- [x] I linted my code on my local machine prior to submission OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code used in an integration test OR N/A.
- [x] All tests ran successfully on my local machine OR N/A.
- [x] All classes, modules, and function contain docstrings OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by kmdeck** [comment]
bors cancel

**Comment by charleskawczynski** [comment]
@kmdeck need to edit the [bors toml](https://github.com/CliMA/ClimaLSM.jl/blob/main/bors.toml#L3-L4)!

**Comment by kmdeck** [comment]
> @kmdeck need to edit the [bors toml](https://github.com/CliMA/ClimaLSM.jl/blob/main/bors.toml#L3-L4)!

thanks!

**Pull request merged**
