### PR TITLE
Apply #195 + suggested fixes

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR applies #195 and applies the suggested fixes.

### CODE REVIEW

**Comment by kmdeck** [comment]
@charleskawczynski is this PR still planned?

**Comment by charleskawczynski** [comment]
Ah, yes, we should revive this if insolation hasn’t been updated yet. I’ll see if I can rebase tomorrow

**Comment by kmdeck** [comment]
> Ah, yes, we should revive this if insolation hasn’t been updated yet. I’ll see if I can rebase tomorrow

no rush! just doing a little housekeeping over here :)

**Comment by juliasloan25** [comment]
@charleskawczynski Is it okay to close this PR? I'm not sure what the suggested fixes in addition to #195 are

**Comment by kmdeck** [comment]
@charleskawczynski is this something you would like me to finish (do we still need it?)

**Comment by juliasloan25** [comment]
superseded by #407

**Pull request closed without merging**
