### PR TITLE
Replace quick Plots.jl plots with pretty Makie plots

### PR DESCRIPTION
**Pull request by AlexisRenchon**
## Purpose 

With this PR we will start using Makie.jl for plotting and producing nice plots instead of quick and dirty plots. 

## To-do

- [x] Script to get data needed for plotting (e.g., model output)
- [ ] Script to make the plots

## Content

Nothing yet, will add progressively

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by AlexisRenchon** [comment]
@Espeer5 I assigned you, just as FYI that this is happening, but you don't have to do anything. 
As this PR progresses, I will start using your `plot_utils.jl" code and split ozark.jl code into 3 scripts: 1. running ClimaLSM, 2. loading all data we need for plotting (e.g., model outputs), 3. make plots

This is all big WIP, but the goal is to make this process easy, comprehensive and clean. Our current experiment was "experimental" indeed, but it is time tidy things up.

**Comment by kmdeck** [comment]
@AlexisRenchon in this PR, could you also change the ground heat flux plot to how we had it before? Something changed in PR #369. This was our previous plotting code:
```
# Ground heat flux
Δz = parent(cds.subsurface.z)[end] - parent(cds.subsurface.z)[end - 2]
first_layer_flux = [
    -parent(sv.saveval[k].soil.κ)[1] * (
        parent(sv.saveval[k].soil.T)[end] -
        parent(sv.saveval[k].soil.T)[end - 2]
    ) / Δz for k in 1:length(sol.t)
]
G_model = [
    (
        parent(sv.saveval[k].soil_shf)[1] + parent(sv.saveval[k].soil_lhf)[1] -
        parent(sv.saveval[k].soil_LW_n)[1] -
        parent(sv.saveval[k].soil_SW_n)[1]
    ) for k in 1:length(sol.t)
]
canopy_G = [
    (
        parent(sv.saveval[k].canopy.energy.shf)[1] +
        parent(sv.saveval[k].canopy.energy.lhf)[1] -
        parent(sv.saveval[k].canopy.radiative_transfer.LW_n)[1] -
        parent(sv.saveval[k].canopy.radiative_transfer.SW_n)[1]
    ) for k in 1:length(sol.t)
]

G_model_avg = diurnal_avg(G_model)
canopy_G_avg = diurnal_avg(canopy_G)

G_data_avg = diurnal_avg(FT.(G)[Int64(t_spinup ÷ DATA_DT):Int64(tf ÷ DATA_DT)])
Rn = (SW_IN .- SW_OUT) .+ (LW_IN .- LW_OUT)
G_alternate_data_avg = diurnal_avg(
    FT.(H .+ LE .- Rn)[Int64(t_spinup ÷ DATA_DT):Int64(tf ÷ DATA_DT)],
)
HplusL_avg =
    diurnal_avg(FT.(H .+ LE)[Int64(t_spinup ÷ DATA_DT):Int64(tf ÷ DATA_DT)])
RminusG_avg =
    diurnal_avg(FT.(Rn .- G)[Int64(t_spinup ÷ DATA_DT):Int64(tf ÷ DATA_DT)])

plt1 = Plots.plot(data_daily_indices, -1 .* G_data_avg, label = "Data: -G")
Plots.plot!(
    plt1,
    data_daily_indices,
    G_alternate_data_avg,
    label = "Data: (H+L-Rn)_site",
    xlabel = "Hour of day",
)
Plots.plot!(plt1, ylabel = "Flux (W/m^2)", title = "Energy balance at the site")

plt2 = Plots.scatter(
    HplusL_avg,
    RminusG_avg,
    label = "Diurnally averaged data",
    xlabel = "H+L",
    ylabel = "R-G",
)
Plots.plot(plt1, plt2, layout = (2, 1))
Plots.savefig(joinpath(savedir, "energy_balance_data.png"))
```

**Comment by kmdeck** [comment]
and, also the latent heat flux. I remember Renato had asked for that before.

**Comment by kmdeck** [comment]
one bug: for the Harvard site, the new scripts plot only data for SW out and LW out. not sure why, since we should have model output?

**Comment by Espeer5** [comment]
> one bug: for the Harvard site, the new scripts plot only data for SW out, LW out, ET. not sure why, since we should have model output? And there is no soil water content plot

Actually the label is just wrong... it plots only the model because there is no data for these for the Harvard site. And for the SWC I just put the 'if' statement in the wrong place so that right now when the data is missing nothing plots at all. These will be quick fixes I can do a really small PR for these in the interim before this one gets done.

**Comment by AlexisRenchon** [comment]
@Espeer5 @kmdeck 
I created a new PR which branches out from the new main which has Ed's recent PR, I will delete this one soon (but not yet). 
As Ed suggest, for now we should just make a quick PR re-adding the old plots we need.

**Comment by Espeer5** [comment]
> @Espeer5 @kmdeck 
> 
> I created a new PR which branches out from the new main which has Ed's recent PR, I will delete this one soon (but not yet). 
> 
> As Ed suggest, for now we should just make a quick PR re-adding the old plots we need. 

I made the changes to re-add the plots and will make a PR as soon as I can test and confirm they work... right now Box.com is having an outage so I can't run anything with the data.

**Pull request closed without merging**
