### PR TITLE
update DSS calls for ClimaCore v0.10.25

### LINKED ISSUE #144: Update DSS usage for ClimaCore v0.10.25
**Is your feature request related to a problem? Please describe.**
As of ClimaCore v0.10.25, `Spaces.dss_interior_faces!` and `Spaces.dss_local_vertices!` have been replaced with `dss2!`. Both ClimaCoupler and ClimaLSM need to be updated to use the new interface. Specifically, the deprecated functions are used in the `Regridder` code of both packages (which should also be moved to a shared location at some point).

Addressed by PR #145 

ClimaCoupler issue [#242](https://github.com/CliMA/ClimaCoupler.jl/issues/242) is the corresponding issue for the coupler.

[Coupler regridder using old functions](https://github.com/CliMA/ClimaCoupler.jl/blob/main/src/Regridder.jl#L50)
[ClimaLSM regridder using old functions](https://github.com/CliMA/ClimaLSM.jl/blob/main/src/Regridder.jl#L50)
[new dss2! function](https://github.com/CliMA/ClimaCore.jl/blob/main/src/Spaces/dss2.jl#L998)
[example using new dss2! which was previously using old functions](https://github.com/CliMA/ClimaCore.jl/blob/95c84fcaf3dc557ff1ebd7c76fc89e2b413efdba/lib/ClimaCoreTempestRemap/src/onlineremap.jl#L59)

### PR DESCRIPTION
**Pull request by juliasloan25**
## Purpose 
Replace function calls to `Spaces.dss_interior_faces!` and `Spaces.dss_local_vertices!` with `Spaces.dss2!` to use the new ClimaCore interface from v0.10.25.

Closes #144.

## To-do
- [x] Replace calls to `dss_interior_faces!` and `dss_local_vertices!` with `dss2!`
- [x] Update Project.toml ClimaCore compat entries

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by kmdeck** [comment]
Does this line need to be updated? https://github.com/CliMA/ClimaLSM.jl/blob/18b9eb4b5cb157154eea283a06b2eaf286e19c06/src/Soil/Soil.jl#L156

**Review by kmdeck — APPROVED** [review]
LGTM, but if we need to update the dss call in the RHS, let's do that in this PR too.

**Comment by juliasloan25** [comment]
> Does this line need to be updated?
> 
> https://github.com/CliMA/ClimaLSM.jl/blob/18b9eb4b5cb157154eea283a06b2eaf286e19c06/src/Soil/Soil.jl#L156

Sriharsha has added functions for backward compatibility [here](https://github.com/CliMA/ClimaCore.jl/blob/main/src/Fields/Fields.jl#L347), so we can continue to use `weighted_dss!` as we have been.

**Pull request merged**
