### PR TITLE
Run CI at every PR

### PR DESCRIPTION
**Pull request by Sbozzolo**
Bors is gone.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
@kmdeck, when this has merged, can you try merging a new PR that removes `bors.toml` to check that everything works as you would expect?

To merge, you can just click the "Enable auto-merge" button on your PR.

**Comment by juliasloan25** [comment]
Just to make sure I understand - this change will run the whole CI pipeline on each commit pushed to Github, right? So in terms of changes to workflow, we'll now need to do the following:
- rebase on main when a PR is ready
- enable auto-merge when we want to merge a rebased PR (instead of `bors r+` as before)

We should also continue using `[skip ci]` frequently to avoid running all these checks unnecessarily (though this isn't new)

**Comment by Sbozzolo** [comment]
> Just to make sure I understand - this change will run the whole CI pipeline on each commit pushed to Github, right? So in terms of changes to workflow, we'll now need to do the following:
> 
> * rebase on main when a PR is ready
> * enable auto-merge when we want to merge a rebased PR (instead of `bors r+` as before)
> 
> We should also continue using `[skip ci]` frequently to avoid running all these checks unnecessarily (though this isn't new)

Yes, correct. We can enable more granularity if needed. For example, we can exclude draft PRs from buildkite.

**Comment by juliasloan25** [comment]
Great, thank you for updating this!

**Review by kmdeck — APPROVED** [review]

**Comment by kmdeck** [comment]
@juliasloan25 @Sbozzolo I updated the permission to require a review before merging, and then approved this. (this was previously a req, Im not sure why it was not enforced here)

Julia, maybe we can talk more about how to skip CI in certain cases.

Gabriele, will try removing bors.toml before the end of the day

**Pull request merged**
